config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Read all tasks
get "tasks", to: "tasks#index", as: :tasks

# Create a task
get "tasks/new", to: "tasks#new", as: :whatever # should be new_task by convention
post "tasks", to: "tasks#create"

# Read one task
get "tasks/:id", to: "tasks#show", as: :task

# Update a task
get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
patch "tasks/:id", to: "tasks#update", as: :update_task

# Delete a task
delete "tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @all_tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # @task is not needed for form, but it is needed for form_for (in partial html)
  end

  def create
    # Task.create title: params[:task_title], details: params[:task_details]
    @task = Task.new(task_params) # should replace with .new(restaurant_params) to use the sanitised params, instead of the dirty one
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @restaurant = Task.find(params[:id])
    @restaurant.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details) # this is called strong params, for security
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title,'Task title:' %>
  <%= f.text_field :title %>

  <%= f.label :details,'Task details:' %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<!-- <form action=<%= update_task_path %> method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Task title: </label>
  <input type="text" name="task[title]" id="title" value=<%= @task.title %>>

  <label for="details">Task details: </label>
  <input type="text" name="task[details]" id="details" value=<%= @task.details %>>

  <input type="submit">
</form>
 -->

 <h1>Edit a task</h1>

 <%= render 'form' %>

app/views/tasks/index.html.erb
<ul>
  <% @all_tasks.each do |task| %>
    <li><%= "completed: #{task.completed} title: #{task.title}" %></a></li>
    <li><%= link_to "See details", task_path(task) %></li>
  <% end %>
</ul>

<p><%= link_to "Add a task", whatever_path %></p>

app/views/tasks/new.html.erb
<!-- <form action="http://localhost:3000/tasks" method="post">
  <input type="text" name="task_title">  we define a parameter with key name = question which is added to params in the webpage specified by the action url
  <input type="text" name="task_details">
  <input type="submit" value="Submit your new task (title and details)">
</form> -->


<!-- <form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Task title: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Task details: </label>
  <input type="text" name="task[details]" id="details">

  <input type="submit">
</form> -->


 <h1>New task</h1>

 <%= render 'form' %>

app/views/tasks/show.html.erb
<p><%= "Details for #{@task.title}: #{@task.details}" %></p>
<p><%= link_to "Edit this task", edit_task_path %></p>
<p><%= link_to "Delete this task", delete_task_path,
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>